### ISSUE TITLE
Баг команды give

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#36]
Above traceback is from an untrapped error. Please file a bug report.
Traceback (most recent call last):
  File "/home/evennia/evennia/evennia/commands/cmdhandler.py", line 417, in _run_command
    ret = yield cmd.func()
  File "/home/evennia/evennia/mudach/commands/command.py", line 383, in func
    caller = self.caller
AttributeError: 'CmdGiveRu' object has no attribute 'rhs'

**Comment by copyright2015** [comment]
исправил

**Comment by op-hui** [comment]
Разложил код на тестовом сервере

**Comment by copyright2015** [comment]
проверил, ошибки нет, русские интерпритации команды работают - "дать", "передать", "отдать"
