### ISSUE TITLE
Создание персонажа, руссификация

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#66]
Сейчас, после того как игрок создает своего персонажа, он видит такое:

Нужно перевсти, скорее всего это хардкод в evennia

```
create test26 test26
A new account 'test26' was created. Welcome!

You can now log with the command 'connect test26 <your password>'.
```

**Comment by copyright2015** [comment]
видел что то подобное в районе evennia/evennia/commans/default/unloggedin.py

**Comment by copyright2015** [comment]
можно перевести по подобию команд

**Comment by op-hui** [comment]
уже https://github.com/op-hui/mu2ch/commit/0b5021e8de06f5d45a75655d500d6f91a8fb9d6f
Остался баг:

```
создать test2 test2
2015-09-13 10:20:13+0000 [AMPProtocol,0,127.0.0.1] [EE] Traceback (most recent call last):
2015-09-13 10:20:13+0000 [AMPProtocol,0,127.0.0.1] [EE]   File "evennia/evennia/mudach/commands/default_cmdsets.py", line 124, in func
2015-09-13 10:20:13+0000 [AMPProtocol,0,127.0.0.1] [EE]     #session.msg(string % (playername, playername))
2015-09-13 10:20:13+0000 [AMPProtocol,0,127.0.0.1] [EE] ValueError: unsupported format character 'U' (0x55) at index 39
Traceback (most recent call last):
  File "evennia/evennia/mudach/commands/default_cmdsets.py", line 124, in func
    #session.msg(string % (playername, playername))
ValueError: unsupported format character 'U' (0x55) at index 39

Случилась проблема, чиним.
```

**Comment by copyright2015** [comment]
ты же их в этот CmdSet положил?
class UnloggedinCmdSet(default_cmds.UnloggedinCmdSet):

**Comment by op-hui** [comment]
Пофиксил баг
https://github.com/op-hui/mu2ch/commit/c5adee0fa55b23b602fbb6f4e08af587b21c317e

Я его не положил в CmdSet, а добавил эту команду незалогиненному пользователю
