### ISSUE TITLE
Баг убить с руками

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#75]
Если объект пытается убить без рук, то вылазит trace

```
Traceback (most recent call last):
  File "evennia/evennia/evennia/commands/cmdhandler.py", line 417, in _run_command
    ret = yield cmd.func()
  File "evennia/evennia/mudach/commands/command.py", line 971, in func
    in_hands = caller.db.hands.contents
AttributeError: 'NoneType' object has no attribute 'contents'

Above traceback is from an untrapped error. Please file a bug report.
```

Баг не критичный, поставил на второй релиз

**Comment by copyright2015** [comment]
сделал проверку на руки
