### ISSUE TITLE
Баг команды drop

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#86]
Баг, я в локации ЕБАНОЕ ничего `@tel /tonone` 
Создал хрущевку в кармане, выложил из кармана и вот что увидел:

```
Traceback (most recent call last):
  File "evennia/evennia/evennia/commands/cmdhandler.py", line 417, in _run_command
    ret = yield cmd.func()
  File "evennia/evennia/mudach/commands/command.py", line 439, in func
    caller.location.msg_contents("%s положил %s." %
AttributeError: 'NoneType' object has no attribute 'msg_contents'
```

**Comment by copyright2015** [comment]
значит что у объекта Ебаное ничего нет метода msg_contents, видимо он не от DefaultObject наследован. Так же у него нет acces метода, его даже черз examine не посмотреть. у него ничего нет...Это же ЕБАНОЕ ничего

**Comment by copyright2015** [comment]
думаю, то, что там ничего не работает это нормально, туда можно отправлять провинившихся
