### ISSUE TITLE
Баг в локации makaba

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#87]
если в makaba написать who
получаю:

```
Traceback (most recent call last):
  File "evennia/evennia/evennia/commands/cmdhandler.py", line 417, in _run_command
    ret = yield cmd.func()
  File "evennia/evennia/mudach/commands/command.py", line 873, in func
    location = puppet.location.key if puppet else "None"
AttributeError: 'NoneType' object has no attribute 'key'

Above traceback is from an untrapped error. Please file a bug report.
```

**Comment by op-hui** [comment]
это происходит в любой локации

**Comment by op-hui** [comment]
пофиксил https://github.com/op-hui/mu2ch/commit/dbd3f9736d376e2ad2b0631eb22060f005791be5
